### PR TITLE
Add example using cycle/http

### PR DESCRIPTION
**Pull request by nakaji-dayo**
#8 

btw, it seems 404 page is not working. it is another problem with this commit.

### CODE REVIEW

**Comment by mciparelli** [comment]
You probably don't want to version `dist` folder.

**Comment by nakaji-dayo** [comment]
thanks.
is `dist` updated by Collaborators (or CI system)?

**Comment by TylorS** [comment]
I generally build the dist/ folder by hand when I do releases

**Comment by TylorS** [comment]
@nakaji-dayo Thanks for this example, is it yet ready to be merged?

**Comment by nakaji-dayo** [comment]
Thanks. I understood.
I rebased to cancel `dist`.

@TylorS Yes, it is ready to be merged.

**Comment by TylorS** [comment]
Merged :+1:

**Comment by TylorS** [comment]
Thanks again

**Pull request merged**
