### PR TITLE
Use rx adapter for diversity

### PR DESCRIPTION
**Pull request by michalvankodev**

### CODE REVIEW

**Comment by michalvankodev** [comment]
Don't forget to bumb history driver version to one which uses rx-adaptor as well
[`@cycle/history`  ](https://github.com/cyclejs/history/pull/18)

**Comment by TylorS** [comment]
The tests need to be updated to use a version of Cycle that passes a stream adapter into the driver. `@cycle/rx-run` would be the easiest to switch to.

**Comment by TylorS** [comment]
Hey @michalvankodev ; you might also be interested in #15

**Comment by TylorS** [comment]
Closing this in favor of #15

**Comment by TylorS** [comment]
Thank you your work though :+1: 

It's seriously appreciated :heart: :heart:

**Pull request closed without merging**
