### PR TITLE
TypeScript and Stream Agnostic

### PR DESCRIPTION
**Pull request by TylorS**
Still a WIP - many tests are still failing.

### CODE REVIEW

**Comment by TylorS** [comment]
This will be ready for merge when https://github.com/staltz/xstream/pull/19 is merged and released.

**Comment by michalvankodev** [comment]
Hey!, staltz/xstream#19 seems to be merged.. Whats the progress on this?

**Comment by TylorS** [comment]
@michalvankodev It's merged but xstream hasn't yet seen a release with it

**Comment by michalvankodev** [comment]
Ok. My next question is why is rx still a dependency and not only a devDependency?

**Comment by michalvankodev** [comment]
Tests passing local.. :fire:

**Comment by TylorS** [comment]
Waiting on travis

**Comment by TylorS** [comment]
Tests are failing with npm v2

**Pull request merged**
